var annotated_dup =
[
    [ "t_buf", "structt__buf.html", "structt__buf" ],
    [ "t_cam", "structt__cam.html", "structt__cam" ],
    [ "t_colour", "structt__colour.html", "structt__colour" ],
    [ "t_cone", "structt__cone.html", "structt__cone" ],
    [ "t_cylinder", "structt__cylinder.html", "structt__cylinder" ],
    [ "t_entities", "structt__entities.html", "structt__entities" ],
    [ "t_equation", "structt__equation.html", "structt__equation" ],
    [ "t_hitrecord", "structt__hitrecord.html", "structt__hitrecord" ],
    [ "t_hittable", "structt__hittable.html", "structt__hittable" ],
    [ "t_img", "structt__img.html", "structt__img" ],
    [ "t_interval", "structt__interval.html", "structt__interval" ],
    [ "t_light", "structt__light.html", "structt__light" ],
    [ "t_menu", "structt__menu.html", "structt__menu" ],
    [ "t_mlx_ptrs", "structt__mlx__ptrs.html", "structt__mlx__ptrs" ],
    [ "t_mouse", "structt__mouse.html", "structt__mouse" ],
    [ "t_numinfo", "structt__numinfo.html", "structt__numinfo" ],
    [ "t_pixel_grid", "structt__pixel__grid.html", "structt__pixel__grid" ],
    [ "t_plane", "structt__plane.html", "structt__plane" ],
    [ "t_putinfo", "structt__putinfo.html", "structt__putinfo" ],
    [ "t_quaternion", "structt__quaternion.html", "structt__quaternion" ],
    [ "t_ray", "structt__ray.html", "structt__ray" ],
    [ "t_render", "structt__render.html", "structt__render" ],
    [ "t_shape", "uniont__shape.html", "uniont__shape" ],
    [ "t_sphere", "structt__sphere.html", "structt__sphere" ],
    [ "t_thread_data", "structt__thread__data.html", "structt__thread__data" ],
    [ "t_vec2f", "structt__vec2f.html", "structt__vec2f" ],
    [ "t_vec2i", "structt__vec2i.html", "structt__vec2i" ],
    [ "t_vec3", "structt__vec3.html", "structt__vec3" ]
];